<a href="https://colab.research.google.com/github/ralsouza/data_manipulation_with_python/blob/master/notebooks/06__exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Group By e Reshape

In [0]:
from google.colab import drive
drive.mount('/content/drive')

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html

In [0]:
import numpy as np
import pandas as pd

In [0]:
cidadesDigitais = pd.read_csv('/content/drive/My Drive/datasets/cidades_digitais.csv', sep = ';', encoding = 'latin-1')

In [0]:
cidadesDigitais.head()

   UF              CIDADE  ...  PONTOS_ATENDIDOS  VALOR_INVESTIDO
0  AC            Tarauacá  ...                 8                0
1  AL     Delmiro Gouveia  ...                43                0
2  AL  Estrela de Alagoas  ...                39                0
3  AM             Autazes  ...                51                0
4  AM   Benjamin Constant  ...                12                0

[5 rows x 8 columns]

In [0]:
cidadesDigitais.count()

UF                      338
CIDADE                  338
IBGE                    338
POPULAÇÃO               338
VALOR_TOTAL_PREVISTO    338
STATUS                  338
PONTOS_ATENDIDOS        338
VALOR_INVESTIDO         338
dtype: int64

In [0]:
del cidadesDigitais['IBGE']

In [0]:
# Aplicando Group By
cidadesUF_1 = cidadesDigitais.groupby('UF')

In [0]:
type(cidadesUF_1)

pandas.core.groupby.generic.DataFrameGroupBy

In [0]:
cidadesUF_1.groups

{'AC': Int64Index([0], dtype='int64'),
 'AL': Int64Index([1, 2], dtype='int64'),
 'AM': Int64Index([3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64'),
 'AP': Int64Index([12, 13, 14, 15, 16, 17], dtype='int64'),
 'BA': Int64Index([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
             35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
            dtype='int64'),
 'CE': Int64Index([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
             68, 69, 70, 71, 72, 73, 74, 75, 76],
            dtype='int64'),
 'DF': Int64Index([77], dtype='int64'),
 'ES': Int64Index([78, 79, 80, 81], dtype='int64'),
 'GO': Int64Index([82, 83, 84, 85, 86, 87, 88, 89, 90, 91], dtype='int64'),
 'MA': Int64Index([ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
             105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117],
            dtype='int64'),
 'MG': Int64Index([118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
             131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
             144, 145],
            dtype='int64'),
 'MS': Int64Index([146, 147, 148], dtype='int64'),
 'MT': Int64Index([149, 150, 151, 152], dtype='int64'),
 'PA': Int64Index([153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
             166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176],
            dtype='int64'),
 'PB': Int64Index([177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
             190, 191, 192, 193, 194],
            dtype='int64'),
 'PE': Int64Index([195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
             208, 209, 210],
            dtype='int64'),
 'PI': Int64Index([211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
             224, 225, 226, 227, 228],
            dtype='int64'),
 'PR': Int64Index([229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
             242, 243, 244, 245],
            dtype='int64'),
 'RJ': Int64Index([246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
             259, 260],
            dtype='int64'),
 'RN': Int64Index([261, 262, 263, 264, 265, 266, 267, 268, 269], dtype='int64'),
 'RO': Int64Index([270, 271], dtype='int64'),
 'RR': Int64Index([272], dtype='int64'),
 'RS': Int64Index([273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
             286, 287, 288],
            dtype='int64'),
 'SC': Int64Index([289, 290, 291, 292, 293, 294], dtype='int64'),
 'SE': Int64Index([295, 296, 297, 298], dtype='int64'),
 'SP': Int64Index([299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
             312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
             325, 326, 327, 328, 329, 330, 331, 332, 333],
            dtype='int64'),
 'TO': Int64Index([334, 335, 336, 337], dtype='int64')}

In [0]:
# Número de grupos
len(cidadesUF_1.groups)

27

In [0]:
ordenaUF = cidadesUF_1.size()
ordenaUF

UF
AC     1
AL     2
AM     9
AP     6
BA    33
CE    26
DF     1
ES     4
GO    10
MA    26
MG    28
MS     3
MT     4
PA    24
PB    18
PE    16
PI    18
PR    17
RJ    15
RN     9
RO     2
RR     1
RS    16
SC     6
SE     4
SP    35
TO     4
dtype: int64

In [0]:
# Getting help
help(pd.DataFrame.sort_values)

Help on function sort_values in module pandas.core.frame:

sort_values(self, by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False)
    Sort by the values along either axis.

    Parameters
    ----------
            by : str or list of str
                Name or list of names to sort by.

                - if `axis` is 0 or `'index'` then `by` may contain index
                  levels and/or column labels.
                - if `axis` is 1 or `'columns'` then `by` may contain column
                  levels and/or index labels.

                .. versionchanged:: 0.23.0

                   Allow specifying index or column level names.
    axis : {0 or 'index', 1 or 'columns'}, default 0
         Axis to be sorted.
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort'}, default 'quicksort'
         Choice of sorting algorithm. See also ndarray.np.sort for more
         information.  `mergesort` is the only stable algorithm. For
         DataFrames, this option is only applied when sorting on a single
         column or label.
    na_position : {'first', 'last'}, default 'last'
         Puts NaNs at the beginning if `first`; `last` puts NaNs at the
         end.
    ignore_index : bool, default False
         If True, the resulting axis will be labeled 0, 1, …, n - 1.

         .. versionadded:: 1.0.0

    Returns
    -------
    sorted_obj : DataFrame or None
        DataFrame with sorted values if inplace=False, None otherwise.

    Examples
    --------
    >>> df = pd.DataFrame({
    ...     'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    ...     'col2': [2, 1, 9, 8, 7, 4],
    ...     'col3': [0, 1, 9, 4, 2, 3],
    ... })
    >>> df
        col1 col2 col3
    0   A    2    0
    1   A    1    1
    2   B    9    9
    3   NaN  8    4
    4   D    7    2
    5   C    4    3

    Sort by col1

    >>> df.sort_values(by=['col1'])
        col1 col2 col3
    0   A    2    0
    1   A    1    1
    2   B    9    9
    5   C    4    3
    4   D    7    2
    3   NaN  8    4

    Sort by multiple columns

    >>> df.sort_values(by=['col1', 'col2'])
        col1 col2 col3
    1   A    1    1
    0   A    2    0
    2   B    9    9
    5   C    4    3
    4   D    7    2
    3   NaN  8    4

    Sort Descending

    >>> df.sort_values(by='col1', ascending=False)
        col1 col2 col3
    4   D    7    2
    5   C    4    3
    2   B    9    9
    0   A    2    0
    1   A    1    1
    3   NaN  8    4

    Putting NAs first

    >>> df.sort_values(by='col1', ascending=False, na_position='first')
        col1 col2 col3
    3   NaN  8    4
    4   D    7    2
    5   C    4    3
    2   B    9    9
    0   A    2    0
    1   A    1    1

In [0]:
# Ordena os grupos por ordem decrescente
ordenaUF.sort_values(ascending=False)

UF
SP    35
BA    33
MG    28
MA    26
CE    26
PA    24
PI    18
PB    18
PR    17
PE    16
RS    16
RJ    15
GO    10
RN     9
AM     9
AP     6
SC     6
ES     4
TO     4
MT     4
SE     4
MS     3
RO     2
AL     2
DF     1
RR     1
AC     1
dtype: int64

In [0]:
cidadesUF_2 = cidadesDigitais.groupby(['UF','STATUS'])
cidadesUF_2

In [0]:
cidadesUF_2.groups

{('AC', 'Sem Previsão'): Int64Index([0], dtype='int64'),
 ('AL', 'Sem Previsão'): Int64Index([1, 2], dtype='int64'),
 ('AM', 'Concluída'): Int64Index([6, 9, 10], dtype='int64'),
 ('AM', 'Sem Previsão'): Int64Index([3, 4, 5, 7, 8, 11], dtype='int64'),
 ('AP', 'Concluída'): Int64Index([16], dtype='int64'),
 ('AP', 'Sem Previsão'): Int64Index([12, 13, 14, 15, 17], dtype='int64'),
 ('BA',
  'Concluída'): Int64Index([32, 34, 35, 37, 38, 39, 42, 49, 50], dtype='int64'),
 ('BA',
  'Sem Previsão'): Int64Index([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 36, 40,
             41, 43, 44, 45, 46, 47, 48],
            dtype='int64'),
 ('CE',
  'Concluída'): Int64Index([53, 54, 55, 60, 63, 68, 69, 71, 73, 75, 76], dtype='int64'),
 ('CE',
  'Sem Previsão'): Int64Index([51, 52, 56, 57, 58, 59, 61, 62, 64, 65, 66, 67, 70, 72, 74], dtype='int64'),
 ('DF', 'Concluída'): Int64Index([77], dtype='int64'),
 ('ES', 'Sem Previsão'): Int64Index([78, 79, 80, 81], dtype='int64'),
 ('GO',
  'Sem Previsão'): Int64Index([82, 83, 84, 85, 86, 87, 88, 89, 90, 91], dtype='int64'),
 ('MA', 'Concluída'): Int64Index([114], dtype='int64'),
 ('MA',
  'Sem Previsão'): Int64Index([ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
             105, 106, 107, 108, 109, 110, 111, 112, 113, 115, 116, 117],
            dtype='int64'),
 ('MG', 'Concluída'): Int64Index([135, 138], dtype='int64'),
 ('MG', 'Em andamento'): Int64Index([134], dtype='int64'),
 ('MG',
  'Sem Previsão'): Int64Index([118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
             131, 132, 133, 136, 137, 139, 140, 141, 142, 143, 144, 145],
            dtype='int64'),
 ('MS', 'Sem Previsão'): Int64Index([146, 147, 148], dtype='int64'),
 ('MT', 'Sem Previsão'): Int64Index([149, 150, 151, 152], dtype='int64'),
 ('PA',
  'Concluída'): Int64Index([158, 160, 161, 162, 164, 170, 174, 175, 176], dtype='int64'),
 ('PA',
  'Sem Previsão'): Int64Index([153, 154, 155, 156, 157, 159, 163, 165, 166, 167, 168, 169, 171,
             172, 173],
            dtype='int64'),
 ('PB',
  'Concluída'): Int64Index([179, 182, 184, 185, 186, 188], dtype='int64'),
 ('PB', 'Em andamento'): Int64Index([178, 180, 181], dtype='int64'),
 ('PB',
  'Sem Previsão'): Int64Index([177, 183, 187, 189, 190, 191, 192, 193, 194], dtype='int64'),
 ('PE', 'Concluída'): Int64Index([196], dtype='int64'),
 ('PE',
  'Sem Previsão'): Int64Index([195, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
             209, 210],
            dtype='int64'),
 ('PI', 'Concluída'): Int64Index([214, 222, 225], dtype='int64'),
 ('PI',
  'Sem Previsão'): Int64Index([211, 212, 213, 215, 216, 217, 218, 219, 220, 221, 223, 224, 226,
             227, 228],
            dtype='int64'),
 ('PR',
  'Concluída'): Int64Index([229, 232, 236, 239, 241, 244, 245], dtype='int64'),
 ('PR', 'Em andamento'): Int64Index([230], dtype='int64'),
 ('PR',
  'Sem Previsão'): Int64Index([231, 233, 234, 235, 237, 238, 240, 242, 243], dtype='int64'),
 ('RJ', 'Concluída'): Int64Index([248], dtype='int64'),
 ('RJ', 'Em andamento'): Int64Index([250, 258], dtype='int64'),
 ('RJ',
  'Sem Previsão'): Int64Index([246, 247, 249, 251, 252, 253, 254, 255, 256, 257, 259, 260], dtype='int64'),
 ('RN', 'Concluída'): Int64Index([269], dtype='int64'),
 ('RN',
  'Sem Previsão'): Int64Index([261, 262, 263, 264, 265, 266, 267, 268], dtype='int64'),
 ('RO', 'Sem Previsão'): Int64Index([270, 271], dtype='int64'),
 ('RR', 'Sem Previsão'): Int64Index([272], dtype='int64'),
 ('RS', 'Concluída'): Int64Index([280, 281, 286, 288], dtype='int64'),
 ('RS', 'Em andamento'): Int64Index([274, 282], dtype='int64'),
 ('RS',
  'Sem Previsão'): Int64Index([273, 275, 276, 277, 278, 279, 283, 284, 285, 287], dtype='int64'),
 ('SC', 'Concluída'): Int64Index([292], dtype='int64'),
 ('SC', 'Sem Previsão'): Int64Index([289, 290, 291, 293, 294], dtype='int64'),
 ('SE', 'Sem Previsão'): Int64Index([295, 296, 297, 298], dtype='int64'),
 ('SP',
  'Concluída'): Int64Index([299, 301, 308, 314, 321, 322, 325, 330], dtype='int64'),
 ('SP', 'Em andamento'): Int64Index([304, 306], dtype='int64'),
 ('SP',
  'Sem Previsão'): Int64Index([300, 302, 303, 305, 307, 309, 310, 311, 312, 313, 315, 316, 317,
             318, 319, 320, 323, 324, 326, 327, 328, 329, 331, 332, 333],
            dtype='int64'),
 ('TO', 'Sem Previsão'): Int64Index([334, 335, 336, 337], dtype='int64')}

In [0]:
# Total agrupado
ordenaUF2 = cidadesUF_2.size(); ordenaUF2

UF  STATUS
AC  Sem Previsão     1
AL  Sem Previsão     2
AM  Concluída        3
    Sem Previsão     6
AP  Concluída        1
    Sem Previsão     5
BA  Concluída        9
    Sem Previsão    24
CE  Concluída       11
    Sem Previsão    15
DF  Concluída        1
ES  Sem Previsão     4
GO  Sem Previsão    10
MA  Concluída        1
    Sem Previsão    25
MG  Concluída        2
    Em andamento     1
    Sem Previsão    25
MS  Sem Previsão     3
MT  Sem Previsão     4
PA  Concluída        9
    Sem Previsão    15
PB  Concluída        6
    Em andamento     3
    Sem Previsão     9
PE  Concluída        1
    Sem Previsão    15
PI  Concluída        3
    Sem Previsão    15
PR  Concluída        7
    Em andamento     1
    Sem Previsão     9
RJ  Concluída        1
    Em andamento     2
    Sem Previsão    12
RN  Concluída        1
    Sem Previsão     8
RO  Sem Previsão     2
RR  Sem Previsão     1
RS  Concluída        4
    Em andamento     2
    Sem Previsão    10
SC  Concluída        1
    Sem Previsão     5
SE  Sem Previsão     4
SP  Concluída        8
    Em andamento     2
    Sem Previsão    25
TO  Sem Previsão     4
dtype: int64

In [0]:
# Sample of original dataset
cidadesDigitais.head()

   UF              CIDADE  ...  PONTOS_ATENDIDOS VALOR_INVESTIDO
0  AC            Tarauacá  ...                 8               0
1  AL     Delmiro Gouveia  ...                43               0
2  AL  Estrela de Alagoas  ...                39               0
3  AM             Autazes  ...                51               0
4  AM   Benjamin Constant  ...                12               0

[5 rows x 7 columns]

In [0]:
# Define the column STATUS as index of dataframe
cidadesUF_3 = cidadesDigitais.set_index('STATUS'); cidadesUF_3

              UF                   CIDADE  ...  PONTOS_ATENDIDOS VALOR_INVESTIDO
STATUS                                     ...
Sem Previsão  AC                 Tarauacá  ...                 8               0
Sem Previsão  AL          Delmiro Gouveia  ...                43               0
Sem Previsão  AL       Estrela de Alagoas  ...                39               0
Sem Previsão  AM                  Autazes  ...                51               0
Sem Previsão  AM        Benjamin Constant  ...                12               0
...           ..                      ...  ...               ...             ...
Sem Previsão  SP     Vargem Grande do Sul  ...                47               0
Sem Previsão  TO     Paraíso do Tocantins  ...                49               0
Sem Previsão  TO  Ponte Alta do Bom Jesus  ...                 9       23.969,90
Sem Previsão  TO           Porto Nacional  ...                61               0
Sem Previsão  TO  São Miguel do Tocantins  ...                20               0

[338 rows x 6 columns]

In [0]:
# Aplicando Group By with hierarquival
cidadesUF_3 = cidadesUF_3.groupby(level='STATUS')

In [0]:
cidadesUF_3.head()

              UF              CIDADE  ...  PONTOS_ATENDIDOS VALOR_INVESTIDO
STATUS                                ...
Sem Previsão  AC            Tarauacá  ...                 8               0
Sem Previsão  AL     Delmiro Gouveia  ...                43               0
Sem Previsão  AL  Estrela de Alagoas  ...                39               0
Sem Previsão  AM             Autazes  ...                51               0
Sem Previsão  AM   Benjamin Constant  ...                12               0
Concluída     AM               Coari  ...                27               0
Concluída     AM          Manacapuru  ...                31      763.009,30
Concluída     AM           Manaquiri  ...                21               0
Concluída     AP      Serra do Navio  ...                21      495.899,00
Concluída     BA            Guanambi  ...                15      441.985,58
Em andamento  MG          Nepomuceno  ...                27               0
Em andamento  PB          Cabaceiras  ...                15               0
Em andamento  PB           Esperança  ...                23               0
Em andamento  PB          Itaporanga  ...                23               0
Em andamento  PR        Bandeirantes  ...                 7               0

[15 rows x 6 columns]

In [13]:
# Grouping by UF and STATUS
cidadesUF_4 = cidadesDigitais.set_index(['UF','STATUS'])
cidadesUF_4 = cidadesUF_4.groupby(level=['UF','STATUS'])
cidadesUF_4.sum()

                 POPULAÇÃO  PONTOS_ATENDIDOS
UF STATUS
AC Sem Previsão      38819                 8
AL Sem Previsão      70303                82
AM Concluída        205666                79
   Sem Previsão     204136               167
AP Concluída          4938                21
   Sem Previsão     107938                81
BA Concluída       1171174               155
   Sem Previsão     532445               559
CE Concluída        658927               218
   Sem Previsão     427514               370
DF Concluída         32148                15
ES Sem Previsão     122164                94
GO Sem Previsão     166045               168
MA Concluída        174267                13
   Sem Previsão     571514               566
MG Concluída         18579                16
   Em andamento      26897                27
   Sem Previsão     465789               533
MS Sem Previsão     118431                94
MT Sem Previsão      77241                97
PA Concluída        620301               189
   Sem Previsão     470578               435
PB Concluída        127879                95
   Em andamento      62733                61
   Sem Previsão     111071               185
PE Concluída         37317                14
   Sem Previsão     342519               297
PI Concluída         37987                45
   Sem Previsão     187556               213
PR Concluída        418078               134
   Em andamento      32639                 7
   Sem Previsão     284252               247
RJ Concluída         13626                11
   Em andamento     167465                35
   Sem Previsão     413049               312
RN Concluída          6218                13
   Sem Previsão      77814               145
RO Sem Previsão      84470                39
RR Sem Previsão      27288                21
RS Concluída        107356                73
   Em andamento      40954                30
   Sem Previsão     300041               265
SC Concluída         29008                18
   Sem Previsão     187416                90
SE Sem Previsão     187455               107
SP Concluída        235299               173
   Em andamento      62857                37
   Sem Previsão     898779               810
TO Sem Previsão     117504               139

In [14]:
# Aggregating with pd.aggregate() and numpy
cidadesUF_4.aggregate([np.sum,np.mean,np.size])

                POPULAÇÃO                     PONTOS_ATENDIDOS
                      sum           mean size              sum       mean size
UF STATUS
AC Sem Previsão     38819   38819.000000    1                8   8.000000    1
AL Sem Previsão     70303   35151.500000    2               82  41.000000    2
AM Concluída       205666   68555.333333    3               79  26.333333    3
   Sem Previsão    204136   34022.666667    6              167  27.833333    6
AP Concluída         4938    4938.000000    1               21  21.000000    1
   Sem Previsão    107938   21587.600000    5               81  16.200000    5
BA Concluída      1171174  130130.444444    9              155  17.222222    9
   Sem Previsão    532445   22185.208333   24              559  23.291667   24
CE Concluída       658927   59902.454545   11              218  19.818182   11
   Sem Previsão    427514   28500.933333   15              370  24.666667   15
DF Concluída        32148   32148.000000    1               15  15.000000    1
ES Sem Previsão    122164   30541.000000    4               94  23.500000    4
GO Sem Previsão    166045   16604.500000   10              168  16.800000   10
MA Concluída       174267  174267.000000    1               13  13.000000    1
   Sem Previsão    571514   22860.560000   25              566  22.640000   25
MG Concluída        18579    9289.500000    2               16   8.000000    2
   Em andamento     26897   26897.000000    1               27  27.000000    1
   Sem Previsão    465789   18631.560000   25              533  21.320000   25
MS Sem Previsão    118431   39477.000000    3               94  31.333333    3
MT Sem Previsão     77241   19310.250000    4               97  24.250000    4
PA Concluída       620301   68922.333333    9              189  21.000000    9
   Sem Previsão    470578   31371.866667   15              435  29.000000   15
PB Concluída       127879   21313.166667    6               95  15.833333    6
   Em andamento     62733   20911.000000    3               61  20.333333    3
   Sem Previsão    111071   12341.222222    9              185  20.555556    9
PE Concluída        37317   37317.000000    1               14  14.000000    1
   Sem Previsão    342519   22834.600000   15              297  19.800000   15
PI Concluída        37987   12662.333333    3               45  15.000000    3
   Sem Previsão    187556   12503.733333   15              213  14.200000   15
PR Concluída       418078   59725.428571    7              134  19.142857    7
   Em andamento     32639   32639.000000    1                7   7.000000    1
   Sem Previsão    284252   31583.555556    9              247  27.444444    9
RJ Concluída        13626   13626.000000    1               11  11.000000    1
   Em andamento    167465   83732.500000    2               35  17.500000    2
   Sem Previsão    413049   34420.750000   12              312  26.000000   12
RN Concluída         6218    6218.000000    1               13  13.000000    1
   Sem Previsão     77814    9726.750000    8              145  18.125000    8
RO Sem Previsão     84470   42235.000000    2               39  19.500000    2
RR Sem Previsão     27288   27288.000000    1               21  21.000000    1
RS Concluída       107356   26839.000000    4               73  18.250000    4
   Em andamento     40954   20477.000000    2               30  15.000000    2
   Sem Previsão    300041   30004.100000   10              265  26.500000   10
SC Concluída        29008   29008.000000    1               18  18.000000    1
   Sem Previsão    187416   37483.200000    5               90  18.000000    5
SE Sem Previsão    187455   46863.750000    4              107  26.750000    4
SP Concluída       235299   29412.375000    8              173  21.625000    8
   Em andamento     62857   31428.500000    2               37  18.500000    2
   Sem Previsão    898779   35951.160000   25              810  32.400000   25
TO Sem Previsão    117504   29376.000000    4              139  34.750000    4

In [15]:
cidadesDigitais.head(3)

   UF              CIDADE  ...  PONTOS_ATENDIDOS VALOR_INVESTIDO
0  AC            Tarauacá  ...                 8               0
1  AL     Delmiro Gouveia  ...                43               0
2  AL  Estrela de Alagoas  ...                39               0

[3 rows x 7 columns]

In [30]:
# Using all columns as index
cidadesUF_5 = cidadesDigitais.set_index(['STATUS', 'CIDADE', 'VALOR_TOTAL_PREVISTO', 'PONTOS_ATENDIDOS', 'VALOR_INVESTIDO','POPULAÇÃO','UF'])
cidadesUF_5

Empty DataFrame
Columns: []
Index: [(Sem Previsão, Tarauacá, 484.547,53, 8, 0, 38819, AC), (Sem Previsão, Delmiro Gouveia, 1.169.381,70, 43, 0, 51997, AL), (Sem Previsão, Estrela de Alagoas, 527.206,83, 39, 0, 18306, AL), (Sem Previsão, Autazes, 1.171.151,92, 51, 0, 37033, AM), (Sem Previsão, Benjamin Constant, 844.586,48, 12, 0, 39484, AM), (Sem Previsão, Careiro, 748.797,08, 17, 0, 36435, AM), (Concluída, Coari, 814.954,75, 27, 0, 83078, AM), (Sem Previsão, Codajás, 757.706,74, 36, 0, 26777, AM), (Sem Previsão, Iranduba, 800.655,02, 30, 0, 45984, AM), (Concluída, Manacapuru, 892.096,87, 31, 763.009,30, 94175, AM), (Concluída, Manaquiri, 636.682,15, 21, 0, 28413, AM), (Sem Previsão, Maraã, 427.516,78, 21, 0, 18423, AM), (Sem Previsão, Amapá, 459.240,58, 15, 0, 8622, AP), (Sem Previsão, Laranjal do Jari, 896.578,06, 17, 0, 45712, AP), (Sem Previsão, Mazagão, 594.149,70, 20, 0, 19571, AP), (Sem Previsão, Porto Grande, 800.403,50, 22, 96.748,00, 19669, AP), (Concluída, Serra do Navio, 590.073,15, 21, 495.899,00, 4938, AP), (Sem Previsão, Vitória do Jari, 687.756,22, 7, 0, 14364, AP), (Sem Previsão, Abaré, 490.227,43, 23, 0, 19574, BA), (Sem Previsão, Anagé, 510.328,56, 15, 0, 20096, BA), (Sem Previsão, Anguera, 441.915,04, 20, 0, 11299, BA), (Sem Previsão, Baianópolis, 499.499,12, 24, 0, 14195, BA), (Sem Previsão, Barra, 1.210.503,86, 46, 0, 54188, BA), (Sem Previsão, Barra do Choça, 747.990,32, 23, 0, 34853, BA), (Sem Previsão, Boa Vista do Tupim, 548.582,05, 28, 0, 18658, BA), (Sem Previsão, Bom Jesus da Serra, 413.597,59, 16, 0, 10554, BA), (Sem Previsão, Brejolândia, 437.370,14, 17, 0, 10698, BA), (Sem Previsão, Buritirama, 486.364,54, 20, 0, 21549, BA), (Sem Previsão, Coronel João Sá, 623.361,08, 27, 0, 17098, BA), (Sem Previsão, Cotegipe, 687.927,70, 36, 0, 14403, BA), (Sem Previsão, Curaçá, 544.494,05, 13, 0, 35208, BA), (Sem Previsão, Encruzilhada, 401.380,67, 17, 0, 20331, BA), (Concluída, Guanambi, 533.416,18, 15, 441.985,58, 85797, BA), (Sem Previsão, Guaratinga, 464.626,92, 17, 0, 22355, BA), (Concluída, Itaberaba, 533.277,38, 16, 409.445,98, 66310, BA), (Concluída, Itabuna, 623.601,85, 17, 463.707,87, 219680, BA), (Sem Previsão, Jeremoabo, 703.108,89, 15, 0, 41100, BA), (Concluída, Juazeiro, 330.262,76, 9, 268.250,96, 218324, BA), (Concluída, Lauro de Freitas, 710.505,26, 21, 625.251,76, 191436, BA), (Concluída, Nilo Peçanha, 467.642,09, 16, 404.337,86, 14188, BA), (Sem Previsão, Pedro Alexandre, 584.854,35, 20, 0, 18135, BA), (Sem Previsão, Piatã, 480.760,30, 25, 0, 18473, BA), (Concluída, Piraí do Norte, 433.787,98, 15, 377.520,78, 10360, BA), (Sem Previsão, Presidente Tancredo Neves, 553.392,15, 26, 0, 27505, BA), (Sem Previsão, Rafael Jambeiro, 441.036,02, 27, 0, 24349, BA), (Sem Previsão, Riacho de Santana, 678.170,45, 33, 0, 4278, BA), (Sem Previsão, Rio do Pires, 473.521,57, 16, 0, 12084, BA), (Sem Previsão, Santa Rita de Cássia, 674.932,84, 17, 0, 28822, BA), (Sem Previsão, São Desidério, 674.932,84, 38, 0, 32640, BA), (Concluída, Uruçuca, 674.090,96, 27, 606.169,36, 21849, BA), (Concluída, Vitória da Conquista, 770.854,49, 19, 650.404,89, 343230, BA), (Sem Previsão, Aiuaba, 608.224,01, 17, 0, 16997, CE), (Sem Previsão, Amontada, 479.642,87, 18, 47.964,29, 42098, CE), (Concluída, Araripe, 451.846,00, 16, 431.175,00, 21289, CE), (Concluída, Barreira, 569.125,00, 20, 503.602,40, 20687, CE), (Concluída, Brejo Santo, 414.096,87, 14, 370.584,00, 48056, CE), (Sem Previsão, Caririaçu, 855.645,37, 38, 0, 26858, CE), (Sem Previsão, Ibaretama, 395.211,05, 19, 117.775,40, 13188, CE), (Sem Previsão, Irauçuba, 602.490,73, 24, 0, 23543, CE), (Sem Previsão, Itatira, 360.412,81, 15, 36.041,28, 20285, CE), (Concluída, Jaguaruana, 234.752,50, 24, 621.943,90, 33469, CE), (Sem Previsão, Jardim, 525.693,75, 15, 0, 27072, CE), (Sem Previsão, Jucás, 811.165,19, 23, 70.519,42, 24479, CE), (Concluída, Maracanaú, 917.610,00, 31, 904.979,30, 221504, CE), (Sem Previsão, Mauriti, 800.468,71, 28, 0, 46113, CE), (Sem Previsão, Missão Velha, 982.422,53, 37, 0, 35240, CE), (Sem Previsão, Ocara, 932.719,89, 33, 93.271,99, 25123, CE), (Sem Previsão, Orós, 776.131,97, 33, 80.526,63, 21394, CE), (Concluída, Quixeramobim, 611.463,00, 20, 558.623,30, 77174, CE), (Concluída, Redenção, 541.709,65, 17, 400.974,74, 80797, CE), (Sem Previsão, Santa Quitéria, 778.971,49, 25, 77.897,15, 43359, CE), (Concluída, Santana do Acaraú, 880.816,43, 27, 317.897,89, 31596, CE), (Sem Previsão, São Benedito, 856.321,05, 25, 85.632,11, 46171, CE), (Concluída, São Gonçalo do Amarante, 465.564,00, 9, 378.125,50, 47297, CE), (Sem Previsão, Tururu, 572.200,39, 20, 57.220,04, 15594, CE), (Concluída, Varjota, 611.787,62, 20, 605.458,80, 18136, CE), (Concluída, Viçosa do Ceará, 521.961,00, 20, 487.065,00, 58922, CE), (Concluída, Estrutural, 421.957,11, 15, 397.718,72, 32148, DF), (Sem Previsão, Afonso Cláudio, 780.654,21, 27, 0, 32454, ES), (Sem Previsão, Ecoporanga, 540.762,65, 7, 0, 24271, ES), (Sem Previsão, Pinheiros, 998.180,59, 30, 0, 26589, ES), (Sem Previsão, Santa Maria de Jetibá, 794.170,33, 30, 0, 38850, ES), (Sem Previsão, Caiapônia, 906.494,09, 13, 0, 18148, GO), (Sem Previsão, Divinópolis de Goiás, 360.499,19, 13, 0, 5020, GO), (Sem Previsão, Itapuranga, 885.670,15, 24, 0, 26639, GO), (Sem Previsão, Jandaia, 549.369,23, 17, 67.038,30, 6272, GO), (Sem Previsão, Matrinchã, 276.226,89, 10, 0, 4500, GO), (Sem Previsão, Nerópolis, 876.496,87, 27, 79.990,00, 27341, GO), (Sem Previsão, Niquelândia, 1.099.715,59, 19, 0, 45243, GO), (Sem Previsão, Paranaiguara, 502.769,75, 9, 0, 9760, GO), (Sem Previsão, Rubiataba, 1.018.336,11, 27, 0, 19832, GO), (Sem Previsão, Teresina de Goiás, 328.258,55, 9, 32.825,86, 3290, GO), (Sem Previsão, Amarante do Maranhão, 945.609,08, 34, 0, 40378, MA), (Sem Previsão, Apicum-Açu, 592.591,70, 20, 0, 17948, MA), (Sem Previsão, Arari, 871.581,16, 30, 0, 29200, MA), (Sem Previsão, Buriti, 677.397,63, 19, 0, 28022, MA), (Sem Previsão, Buriti Bravo, 928.283,68, 34, 0, 23375, MA), (Sem Previsão, Buritirana, 465.860,24, 18, 0, 15100, MA), (Sem Previsão, Cajari, 592.591,70, 20, 0, 18943, MA), (Sem Previsão, Cândido Mendes, 418.515,74, 15, 0, 19702, MA), ...]

[338 rows x 0 columns]

In [0]:
cidadesUF_5 = cidadesUF_5.groupby(level=['STATUS','VALOR_TOTAL_PREVISTO','VALOR_INVESTIDO','UF'])

In [32]:
cidadesUF_5.sum()

Empty DataFrame
Columns: []
Index: [(Concluída, 1.023.839,75, 836.808,10, PA), (Concluída, 1.024.440,40, 958.295,60, RS), (Concluída, 234.752,50, 189.134,16, RS), (Concluída, 234.752,50, 621.943,90, CE), (Concluída, 266.802,12, 206.113,40, PB), (Concluída, 270.085,77, 204.232,98, PR), (Concluída, 285.842,80, 240.879,90, MG), (Concluída, 290.426,96, 288.464,55, MG), (Concluída, 324.598,35, 0, PI), (Concluída, 330.262,76, 268.250,96, BA), (Concluída, 335.161,32, 260.844,47, SP), (Concluída, 352.575,00, 0, RJ), (Concluída, 411.047,68, 139.501,10, RN), (Concluída, 414.096,87, 370.584,00, CE), (Concluída, 419.387,54, 364.650,70, PB), (Concluída, 421.957,11, 397.718,72, DF), (Concluída, 424.830,85, 130.558,10, PA), (Concluída, 428.579,50, 377.463,70, PB), (Concluída, 433.787,98, 377.520,78, BA), (Concluída, 438.445,29, 354.671,92, SP), (Concluída, 451.846,00, 431.175,00, CE), (Concluída, 464.730,35, 422.459,60, RS), (Concluída, 465.564,00, 378.125,50, CE), (Concluída, 466.649,65, 393.175,34, PR), (Concluída, 467.642,09, 404.337,86, BA), (Concluída, 485.264,10, 410.386,30, PE), (Concluída, 499.010,00, 0, PI), (Concluída, 509.908,95, 191.140,00, PR), (Concluída, 521.961,00, 487.065,00, CE), (Concluída, 522.826,11, 242.272,00, PA), (Concluída, 533.277,38, 409.445,98, BA), (Concluída, 533.416,18, 441.985,58, BA), (Concluída, 538.580,75, 432.278,00, MA), (Concluída, 539.153,44, 490.024,60, PB), (Concluída, 541.709,65, 400.974,74, CE), (Concluída, 550.508,58, 526.144,00, PB), (Concluída, 557.090,75, 413.613,50, PA), (Concluída, 559.184,35, 218.948,00, PA), (Concluída, 566.980,26, 530.358,64, RS), (Concluída, 569.125,00, 503.602,40, CE), (Concluída, 584.153,42, 245.305,00, SP), (Concluída, 590.073,15, 495.899,00, AP), (Concluída, 597.782,80, 568.129,52, SC), (Concluída, 598.959,00, 0, PI), (Concluída, 600.900,72, 509.997,10, PB), (Concluída, 611.463,00, 558.623,30, CE), (Concluída, 611.787,62, 605.458,80, CE), (Concluída, 623.601,85, 463.707,87, BA), (Concluída, 636.682,15, 0, AM), (Concluída, 674.090,96, 606.169,36, BA), (Concluída, 679.270,00, 388.840,00, PR), (Concluída, 680.553,70, 650.546,40, PR), (Concluída, 702.701,56, 0, SP), (Concluída, 710.505,26, 625.251,76, BA), (Concluída, 730.256,00, 674.964,22, SP), (Concluída, 740.416,36, 711.125,40, SP), (Concluída, 746.189,75, 289.252,00, PA), (Concluída, 770.854,49, 650.404,89, BA), (Concluída, 781.824,00, 452.400,00, PR), (Concluída, 783.863,93, 647.554,60, PA), (Concluída, 814.954,75, 0, AM), (Concluída, 831.691,60, 772.690,54, SP), (Concluída, 875.603,00, 800.518,00, PR), (Concluída, 880.816,43, 317.897,89, CE), (Concluída, 892.096,87, 763.009,30, AM), (Concluída, 901.124,75, 722.265,70, PA), (Concluída, 917.610,00, 904.979,30, CE), (Concluída, 926.456,65, 770.171,60, PA), (Concluída, 957.039,36, 958.073,92, SP), (Em andamento, 279.409,70, 0, PR), (Em andamento, 355.867,86, 0, PB), (Em andamento, 382.013,20, 0, RS), (Em andamento, 451.240,30, 0, SP), (Em andamento, 477.934,00, 0, RJ), (Em andamento, 565.686,00, 0, RS), (Em andamento, 600.951,92, 0, RJ), (Em andamento, 621.901,86, 0, SP), (Em andamento, 643.482,51, 0, PB), (Em andamento, 649.011,44, 0, PB), (Em andamento, 650.576,00, 0, MG), (Sem Previsão, 1.015.248,54, 0, SP), (Sem Previsão, 1.018.336,11, 0, GO), (Sem Previsão, 1.019.380,74, 0, PA), (Sem Previsão, 1.035.208,77, 0, RO), (Sem Previsão, 1.038.572,22, 0, RR), (Sem Previsão, 1.050.595,61, 0, MS), (Sem Previsão, 1.050.686,93, 0, RJ), (Sem Previsão, 1.055.014,86, 0, PE), (Sem Previsão, 1.065.228,26, 0, PA), (Sem Previsão, 1.067.635,12, 0, PR), (Sem Previsão, 1.072.570,70, 0, MG), (Sem Previsão, 1.084.905,79, 0, MT), (Sem Previsão, 1.097.593,40, 0, PR), (Sem Previsão, 1.099.715,59, 0, GO), (Sem Previsão, 1.101.168,76, 0, TO), (Sem Previsão, 1.116.548,04, 0, RS), (Sem Previsão, 1.119.305,92, 0, SP), (Sem Previsão, 1.120.514,49, 92.707,50, MT), (Sem Previsão, 1.132.841,73, 0, RO), (Sem Previsão, 1.135.692,68, 0, SP), ...]

[336 rows x 0 columns]